version: '3'

services:
  db:
    image: postgres # use latest official postgres version
    env_file:
      - postgres.env # configure postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  web:
    build: .
    command: python main.py
    volumes:
      - .:/usr/src/app
    env_file:
    - app.env
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  pg-data: