"""update event table

Revision ID: 2650f55b5279
Revises: c842d131119d
Create Date: 2022-07-17 18:45:21.622224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2650f55b5279'
down_revision = 'c842d131119d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='score_event_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='score_pkey')
    )
    # ### end Alembic commands ###
