"""create score table

Revision ID: c842d131119d
Revises: bfaca5d4fa3b
Create Date: 2022-07-16 19:42:52.798072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c842d131119d'
down_revision = 'bfaca5d4fa3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
